Add geo location
mohitahlawat2001/Loco-Musica pull request #8
Opened 2024-10-03 08:39 UTC by prayag78

### Add Geolocation to Fetch Coordinates 

1. Add geo location for fetch coordinate and then add them to api
2. Add default coordinates in case the user denies location access

![Screenshot 2024-10-03 131015](https://github.com/user-attachments/assets/c1156f76-2fda-41f6-8d8c-6cdd13c91847)

2024-10-03 08:48 UTC, mohitahlawat2001 reviewed
not able to see food item , send photo with food items , after giving access to geo location

2024-10-03 10:01 UTC, mohitahlawat2001 requested changes
did to handle if api doesnt give data for any location outside of india 
what you should ,

2024-10-03 10:03 UTC, prayag78 commented
I just added the default Coordinates of india.

On Thu, 3 Oct, 2024, 3:31 pm Mohit ahlawat, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> did to handle if api doesnt give data for any location outside of india
> what you should ,
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mohitahlawat2001/Loco-Musica/pull/8#pullrequestreview-2345167903>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BI2NWWUA37O4NDDX5KZUAEDZZUIYTAVCNFSM6AAAAABPJJNGVWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGNBVGE3DOOJQGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-03 10:09 UTC, mohitahlawat2001 requested changes
why you commented code , remove it

2024-10-03 10:10 UTC, mohitahlawat2001 commented on src/components/Body.js
> +const defaultLat = "21.1702401"; // Default latitude for India
make these inside contants file

2024-10-03 10:12 UTC, mohitahlawat2001 requested changes

2024-10-03 10:12 UTC, mohitahlawat2001 commented on src/components/Body.js
> +  const [location, setLocation] = useState({ lat: defaultLat, lon: defaultLon });
use can use useMemo instead , more optimize

2024-10-03 10:12 UTC, mohitahlawat2001 commented on src/components/Body.js
> +      const apiUrl = `https://foodfire.onrender.com/api/restaurants?lat=${lat}&lng=${lon}&page_type=DESKTOP_WEB_LISTING`;
take this url from constant file

2024-10-04 03:23 UTC, mohitahlawat2001 approved these changes

2024-10-04 03:25 UTC, merged